name: Documentation Analysis
on:
  workflow_call:
    inputs:
      dir:
        required: false
        type: string
        default: '.'

jobs:
  dartdoc_analysis:
    name: Documentation Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: beta

      - name: Get dependencies
        run: flutter pub get

      - name: Activate dartdoc
        run: flutter pub global activate dartdoc

      - name: Run dartdoc
        run: flutter pub global run dartdoc ${{ inputs.dir }} --no-generate-docs -q
