name: Web Integration Test
on:
  workflow_call:
    inputs:
      dir:
        required: false
        type: string
        default: '.'
      environment:
        required: false
        type: string
    secrets:
      args:
        required: false

jobs:
  web_integration_test:
    name: Web Integration Test
    environment: ${{ inputs.environment }}
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ${{ inputs.dir }}
        shell: pwsh

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: beta

      - name: Run integration tests on Chrome
        run: |
          echo "ID=$((Start-Job {chromedriver --port=4444 --enable-chrome-logs}).Id)" >> $GITHUB_ENV

          flutter driver --driver test_driver/integration_test.dart `
            --target ./integration_test/dynamic_cached_fonts_example_test.dart `
            --device-id web-server `
            --browser-name chrome `
            --release ${{ secrets.args }}

      - name: Print Chrome browser logs
        run: Receive-Job -Id ${{ env.ID }}
