name: Unit Test
on:
  workflow_call:
    inputs:
      dir:
        required: false
        type: string
        default: '.'

jobs:
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.dir }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: beta

      - name: Run unit tests
        run: flutter test
