name: Web Integration Test
on:
  workflow_call:
    inputs:
      dir:
        required: false
        type: string
        default: '.'
      environment:
        required: false
        type: string
      test_filename:
        required: true
        type: string
    secrets:
      args:
        required: false

jobs:
  web_integration_test:
    name: Web Integration Test
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.dir }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: beta

      - name: Run integration tests on Chrome
        run: |
          chromedriver --port=4444 --enable-chrome-logs --log-path=chrome_logs.log &

          flutter driver --driver test_driver/integration_test.dart \
            --target ./integration_test/${{ inputs.test_filename }} \
            --device-id web-server \
            --browser-name chrome \
            --release ${{ secrets.args }}

      - name: Print Chrome browser logs
        run: cat chrome_logs.log
