name: Unit Test
on:
  workflow_call:
    inputs:
      dir:
        required: false
        type: string
        default: '.'
      coverage:
        required: false
        type: boolean
        default: true
    secrets:
      codecov_token:
        required: false

jobs:
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.dir }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: beta

      - name: Run unit tests
        run: flutter test --coverage
      
      - name: Codecov
        if: ${{ inputs.coverage }}
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.codecov_token }}
          file: ${{ inputs.dir }}/coverage/lcov.info
          flags: unit
          fail_ci_if_error: true
