# Requirements:
# - Add 'jobs.<job_id>.concurrency' to caller workflows with 'cancel-in-progress' set to true.
# concurrency:
#   group: Example Github Pages
#   cancel-in-progress: true
#
# - Enable 'write' permission for 'contents'
# permissions:
#   contents: write

name: Deploy to Github Pages
on:
  workflow_call:
    inputs:
      dir:
        required: false
        type: string
        default: '.'
      environment:
        required: false
        type: string
      wait_on_tests:
        required: false
        type: boolean
        default: true
      dry_run:
        required: false
        type: boolean
        default: false
    secrets:
      args:
        required: false

jobs:
  build_and_deploy:
    name: Build and Deploy to Github Pages
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.dir }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: beta

      - name: Get current workflow name
        uses: octokit/request-action@v2.1.4
        id: check_name
        with:
          route: GET /repos/{owner}/{repo}/check-runs/{check_run_id}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          check_run_id: ${{ github.run_id }}

      - name: Wait on tests
        if: ${{ inputs.wait_on_tests }}
        uses: lewagon/wait-on-check-action@v1.1.1
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          running-workflow-name: ${{ fromJson(steps.check_name.outputs.data).name }}
          allowed-conclusions: success,skipped,cancelled,waiting

      - name: Build app for web
        run: |
          flutter build web \
            --base-href /${{ github.event.repository.name }}/ \
            --no-source-maps \
            --release ${{ secrets.args }}

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ${{ inputs.dir }}/build/web
          dry-run: ${{ inputs.dry_run }}
