# Requirements:
# - Enable 'write' permission for 'checks'
# permissions:
#   checks: write

name: Pana Code Analysis
on:
  workflow_call:
    inputs:
      dir:
        required: false
        type: string
        default: '.'
      min_points:
        required: false
        type: number

jobs:
  pana_analyze:
    name: Analyze package with Pana
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.dir }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Format code for tests
        run: dart format .

      - name: Analyze package with pana
        uses: axel-op/dart-package-analyzer@v3
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: ${{ inputs.dir }}

      - name: Calculate Result
        run: |
          [ "${{ inputs.min_points }}" -ne "0" ] \
          && MIN_SCORE=${{ inputs.min_points }} \
          || MIN_SCORE=${{ steps.analysis.outputs.total_max }}
          if [[ ${{ steps.analysis.outputs.total }} -lt $MIN_SCORE ]]
          then
            echo "::error::Pub score test failed. Achieved score of ${{ steps.analysis.outputs.total }} is less than expected minimum score of $MIN_SCORE"
            exit 1
          else
            echo "Pub score test passed!"
          fi
