# Requirements:
# - Enable 'write' permission for 'checks'
# permissions:
#   checks: write

name: Pub pre-check
on:
  workflow_call:
    inputs:
      dir:
        required: false
        type: string
        default: '.'

jobs:
  publish_to_pub_pre_check:
    name: Publish to Pub pre-check
    if: contains(github.event.pull_request.labels.*.name, 'release :tada:')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Run publisher in dry run mode
        run: dart pub lish --dry-run --directory ${{ inputs.dir }} | tee publish.log

      - name: Set output
        run: echo "::set-output name=logs::$(cat publish.log)"

  post_result:
    name: Post pre-check result
    runs-on: ubuntu-latest

    needs: [ publish_to_pub_pre_check ]

    steps:
      - name: Post pre-check result to check run
        uses: actions/github-script@v6
        env:
          STATUS: ${{ needs.publish_to_pub_pre_check.result == 'success' }}
          LOGS: ${{ needs.publish_to_pub_pre_check.outputs.logs }}
        with:
          script: |
            const { STATUS, LOGS } = process.env;
            const { owner, repo } = context.repo;

            await github.rest.checks.create({
              owner, repo,
              name: 'Release Pre-Check',
              head_sha: context.sha,
              status: 'completed',
              conclusion: STATUS ? 'success' : 'failure',
              output: {
                title: 'Logs for Pre-Check: Publish to Pub',
                text: LOGS,
                summary: STATUS
                  ? 'Publish to Pub dry run successful! :tada:'
                  : 'Publish to Pub failed :frowning_face: Output logs -',
              },
                completed_at: new Date().toISOString(),
            })
