# Requirements:
# - Enable 'write' permission for 'checks'
# permissions:
#   checks: write

name: Pub pre-check
on:
  workflow_call:
    inputs:
      dir:
        required: false
        type: string
        default: '.'

jobs:
  publish_to_pub_pre_check:
    name: Publish to Pub pre-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Run publisher in dry run mode
        id: publisher
        continue-on-error: true
        run: |
          dart pub lish --dry-run --directory ${{ inputs.dir }} | tee publish.log
          CODE=$?
          echo "LOGS<<EOF" >> $GITHUB_ENV
          cat publish.log >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          [[ "$CODE" == "65" ]] && exit 1

      - name: Post pre-check result to check run
        uses: actions/github-script@v6
        with:
          script: |
            const { LOGS } = process.env
            const { owner, repo } = context.repo;

            const { data } = await github.rest.checks.create({
              owner, repo,
              name: 'Release Pre-Check',
              head_sha: context.sha,
              status: 'completed',
              conclusion: '${{ steps.publisher.outcome }}',
              output: {
                title: 'Logs for Pre-Check: Publish to Pub',
                text: LOGS,
                summary: '${{ steps.publisher.outcome }}' === 'success'
                  ? 'Publish to Pub dry run successful! :tada:'
                  : 'Publish to Pub failed :frowning_face:',
              },
                completed_at: new Date().toISOString(),
            })

            console.log(`Output: ${data.html_url}`)
