name: Verify Formatting

on:
  workflow_call:
    inputs:
      dir:
        required: false
        type: string
        default: '.'
      line_length:
        required: false
        type: number
        default: 100

jobs:
  verify_formatting:
    name: Verify Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Verify formatting
        run: dart format --line-length=${{ inputs.line_length }} --output=none --set-exit-if-changed ${{ inputs.dir }}
